server:
  port: 8090

jwt:
  secret-key: 586E327235753778214125442A472D4B6150645367566B597033733676397924
  lifetime: 86400000

spring:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/uas

  liquibase:
    enabled: true
