spring:
  application:
    name: news

  profiles:
    active: dev

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    openfeign:
      client:
        config:
          users-service:
            url: http://localhost:8090