server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dtalyanin/ClevertecNewsSystemConfigs.git
          default-label: master
          search-paths: configs